version: "3.7"
volumes:
    postgres-data:
    pgadmin-data:
networks:
    frontend:
    backend:
services:
    proxy:
        image: nginx:latest
        container_name: proxy
        hostname: proxy
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: laravel:latest
        hostname: php
        restart: always
        volumes:
            - ./:/var/www/app
        networks:
            - backend
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: Pass#12345
            POSTGRES_USER: postgres
            POSTGRES_DB: laraveldb
            PGDATA: /var/lib/postgresql/data
        networks:
            - backend
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        hostname: pgadmin4
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: tidop@tidop.es
            PGADMIN_DEFAULT_PASSWORD: Pass#12345
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - backend
